
library(shiny)
library(bslib)
library(here)

# Define UI for application that draws a histogram
ui <- page_navbar(
  title = "Estimating MDMA Monopoly Revenues",
  theme = bs_theme(version = 5),
  
  # ---- PAGE 1: Assumptions ----
    nav_panel(
      "Assumptions",
    tags$p(
      tags$strong("This shiny app compliments the report: Counting the Returns MDMA quickscan, by the municipality of Amsterdam"),
      "The quickscan provides an estimate of the potential revenue that could be generated by a state-run MDMA monopoly in the Netherlands. As there is no precedent for a regulated MDMA market, our analysis is partly based on educated guesses. For instance, we have made assumptions regarding the production costs of MDMA and the proportion of consumers who would switch to a regulated market. This app enables you to easily calculate your own revenue estimates for a state-run MDMA monopoly, based on various assumptions. For more elaborate definitions, please consult the accompanying report.",
      tags$br(),
      tags$p(
        style = "margin-top: 1rem;",
        "Revenue is calculated using the following formula: ",
        tags$span(
          style = "white-space: nowrap;",
          tags$em("Number of consumers"), " × ",
          tags$em("Frequency"), " × ",
          tags$em("Intensity"), " × ",
          tags$em("Market capture"), " × (",
          tags$em("Price"), " − ", tags$em("Cost"), ")."
        )
      )
    ),
    hr(),
    
    fluidRow(
      column(
        width = 4,
        h4("Intensity"),
        h5("The average number of pills consumed per session."),
        numericInput("intensity_mean", "Mean pills per session (μ)", value = 2, min = 0, step = 0.1),
        numericInput("intensity_sd", "Spread (sd)", value = 0.5, min = 0, step = 0.1)
      ),
      column(
        width = 4,
        h4("Market capture"),
        h5("The proportion of current MDMA consumers that would buy from a regulated market."),
        numericInput("mkr_point", "Point estimate", value = 0.8, min = 0, max = 1, step = 0.01),
        sliderInput("mkr_range", "Range", min = 0, max = 1, value = c(0.4, 0.9), step = 0.01)
      ),
      column(
        width = 4,
        h4("Price & Cost (€/pill)"),
        h5("Cost refers to the total marginal cost per pill."),
        numericInput("price_point", "Price point estimate", value = 5, min = 0, step = 0.1),
        sliderInput("price_range", "Price range", min = 0, max = 20, value = c(3, 8), step = 0.1),
        numericInput("cost_point", "Cost point estimate", value = 2, min = 0, step = 0.1),
        sliderInput("cost_range", "Cost range", min = 0, max = 20, value = c(1, 8), step = 0.1)
      )
    ),
    hr(),
    fluidRow(
      column(
        width = 12,
        h4("Point estimate (using point inputs)"),
        textOutput("point_estimate", container = h2),
        uiOutput("neg_revenue_badge")
      )
    )
  ),
  
  # ---- PAGE 2 (blank for now) under a menu ----
  nav_menu(
    "More",
    nav_panel(
      "Frequency (coming soon)",
      fluidPage(
        h4("Frequency"),
        p("This page will host frequency inputs, data loading, and related outputs.")
      )
    )
  )
)

server <- function(input, output, session) {
  
  # Import empirical frequency 
  party_panel <- read.csv(here::here("data", "Party_Panel.csv"), check.names = FALSE)
  
  # drop the last five rows (your comment says five, not one)
  if (nrow(party_panel) >= 5) {
    party_panel <- party_panel[seq_len(nrow(party_panel) - 5), ]
  }
  
  party_panel[] <- lapply(party_panel, function(x) as.numeric(x))
  
  fr <- with(party_panel, sum(Gebruik * Frequencies, na.rm = TRUE) / sum(Frequencies, na.rm = TRUE))
  
  # Point estimate uses point inputs only
  revenue_point <- reactive({
    mkr  <- input$mkr_point
    p    <- input$price_point
    cst  <- input$cost_point
    inten <- input$intensity_mean
    
    # Ensure non-negative and handle price < cost gracefully (can produce negative revenue)
    mkr <- max(0, min(1, mkr))
    p   <- max(0, p)
    cst <- max(0, cst)
    inten <- max(0, inten)
    
    number_consumers * fr * inten * mkr * (p - cst)
  })
  
  output$point_estimate <- renderPrint({
    # formatted output
    val <- revenue_point()
    paste0("€ ", format(round(val, 0), big.mark = ","))
  })
  
}

# Run the application 
shinyApp(ui = ui, server = server)
