
library(shiny)
library(bslib)
library(here)

# Define UI for application that draws a histogram
ui <- page_navbar(
  title = "Estimating MDMA Monopoly Revenues",
  theme = bs_theme(version = 5),
  
  nav_panel(
    "About",
    card(
      card_header("Background & Formula"),
      tags$p(
        tags$strong("This shiny app compliments the report: Counting the Returns MDMA quickscan, by the municipality of Amsterdam"),
        "The quickscan provides an estimate of the potential revenue that could be generated by a state-run MDMA monopoly in the Netherlands. As there is no precedent for a regulated MDMA market, our analysis is partly based on educated guesses. For instance, we have made assumptions regarding the production costs of MDMA and the proportion of consumers who would switch to a regulated market. This app enables you to easily calculate your own revenue estimates for a state-run MDMA monopoly, based on various assumptions. For more elaborate definitions, please consult the accompanying report.",
        tags$br(),
        tags$p(
          style = "margin-top: 1rem;",
          "Revenue is calculated using the following formula: ",
          tags$span(
            style = "white-space: nowrap;",
            tags$em("Number of consumers"), " × ",
            tags$em("Frequency"), " × ",
            tags$em("Intensity"), " × ",
            tags$em("Market capture"), " × (",
            tags$em("Price"), " − ", tags$em("Cost"), ")."
          )
        )
      )
    )
  ),
  
  # ---- PAGE 1: Assumptions ----
  nav_panel(
    "Assumptions",
    layout_sidebar(
      
      sidebar = sidebar(
        title = "Estimates",
        open = TRUE,            # keep sidebar open by default
        width = 360,            # tweak to taste
        
        accordion(
          id = "assumption_panels", 
          multiple = FALSE,      # only one panel open at a time
          open = c("Simulation settings"),  # default open panels
        
          # --- Inputs ---
          accordion_panel(
            "Number of consumers",
            p(class = "text-muted small", "Estimated number of annual MDMA consumers in the Netherlands."),
            numericInput("num_consumers", "Number of consumers", value = 550000, min = 0, step = 1000),
            sliderInput("num_consumers_range", "Range", min = 0, max = 18000000, value = c(300000, 800000), step = 1000)
          ),
          
          accordion_panel(
          "Intensity",
          p(class = "text-muted small", "Average number of pills per session."),
          numericInput("intensity_mean", "Mean pills per session (μ)", value = 2, min = 0, step = 0.1),
          numericInput("intensity_sd",   "Spread (sd)",               value = 0.5, min = 0, step = 0.1),
          ),
          
          accordion_panel(
          "Market capture",
          p(class = "text-muted small", "Proportion of consumers who switch to the regulated market."),
          numericInput("mkr_point", "Point estimate", value = 0.8, min = 0, max = 1, step = 0.01),
          sliderInput("mkr_range", "Range", min = 0, max = 1, value = c(0.4, 0.9), step = 0.01),
          ),
          
          accordion_panel(
          "Price & Cost (€/pill)",
          p(class = "text-muted small", "Cost is total marginal cost per pill."),
          numericInput("price_point", "Price point estimate", value = 5, min = 0, step = 0.1),
          sliderInput("price_range", "Price range", min = 0, max = 20, value = c(3, 8), step = 0.1),
          numericInput("cost_point", "Cost point estimate", value = 2, min = 0, step = 0.1),
          sliderInput("cost_range", "Cost range", min = 0, max = 20, value = c(1, 8), step = 0.1)
          ),
          
          accordion_panel(
            "Simulation settings",
            h6(class = "text-muted", "Control Monte Carlo sampling."),
            numericInput(
              "sim_n", "Number of draws (n)",
              value = 10000, min = 100, max = 1e6, step = 1000
            ),
            numericInput(
              "sim_seed", "Random seed",
              value = 1234, min = 0, step = 1
            ),
            helpText("Larger n gives smoother plots but takes longer to compute.")
          )
        ),
      
      
      # ---- Main content (outputs) ----
      card(
        card_header("Point estimate (using point inputs)"),
        h1(textOutput("point_estimate"), class = "display-5"),
        p(class = "text-muted small",
          "Revenue = Number of consumers × Frequency x Intensity × Market capture × (Price − Cost)."
        )
      )
    ),
      
      # ---- Simulation results ----
      card(
        card_header("Simulation results"),
        plotOutput("revenue_boxplot", height = "420px")
      )
    )
  ),
  
  # ---- PAGE 2 (blank for now) under a menu ----
  nav_menu(
    "More",
    nav_panel(
      "Frequency (coming soon)",
      fluidPage(
        h4("Frequency"),
        p("This page will host frequency inputs, data loading, and related outputs.")
      )
    )
  )
)

server <- function(input, output, session) {
  
  # Import empirical frequency 
  party_panel <- read.csv(here::here("data", "Party_Panel.csv"), check.names = FALSE)
  
  # drop the last five rows (your comment says five, not one)
  if (nrow(party_panel) >= 5) {
    party_panel <- party_panel[seq_len(nrow(party_panel) - 5), ]
  }
  
  party_panel[] <- lapply(party_panel, function(x) as.numeric(x))
  
  fr <- with(party_panel, sum(Gebruik * Frequencies, na.rm = TRUE) / sum(Frequencies, na.rm = TRUE))
  
  # Point estimate uses point inputs only
  revenue_point <- reactive({
    mkr  <- input$mkr_point
    p    <- input$price_point
    cst  <- input$cost_point
    inten <- input$intensity_mean
    
    # Ensure non-negative and handle price < cost gracefully (can produce negative revenue)
    mkr <- max(0, min(1, mkr))
    p   <- max(0, p)
    cst <- max(0, cst)
    inten <- max(0, inten)
    
    number_consumers * fr * inten * mkr * (p - cst)
  })
  
  output$point_estimate <- renderPrint({
    # formatted output
    val <- revenue_point()
    paste0("€ ", format(round(val, 0), big.mark = ","))
  })
  
  # ---- Monte Carlo simulation (reactive) ----
  sim_draws <- reactive({
    
    n <- as.integer(max(100, min(1e6, input$sim_n %||% 10000)))
    seed <- as.integer(input$sim_seed %||% 1234)
    
    set.seed(seed)  # we can make this user-set later
    
    # Inputs
    inten_mean <- max(0, input$intensity_mean)
    inten_sd   <- max(0, input$intensity_sd)
    
    mkr_lower  <- max(0, min(1, input$mkr_range[1]))
    mkr_upper  <- max(0, min(1, input$mkr_range[2]))
    
    price_lower <- max(0, input$price_range[1])
    price_upper <- max(price_lower, input$price_range[2])  # ensure upper >= lower
    
    cost_lower  <- max(0, input$cost_range[1])
    cost_upper  <- max(cost_lower, input$cost_range[2])
    
    # Draws (vectorized)
    intensity <- rnorm(n, mean = inten_mean, sd = inten_sd)
    market    <- runif(n, min = mkr_lower,   max = mkr_upper)
    price     <- runif(n, min = price_lower, max = price_upper)
    cost      <- runif(n, min = cost_lower,  max = cost_upper)
    
    # Frequency draws from party_panel (first 21 rows)
    freq <- sample(
      x       = party_panel$Gebruik[1:21],
      size    = n,
      replace = TRUE,
      prob    = party_panel$Frequencies[1:21]
    )
    
    revenue <- number_consumers * freq * intensity * market * (price - cost)
    revenue
  })
  
  # ---- Point estimate with frequency mean (reactive, using point inputs) ----
  revenue_estimate_freq <- reactive({
    number_consumers * frequency_mean *
      max(0, input$intensity_mean) *
      max(0, min(1, input$mkr_point)) *
      (max(0, input$price_point) - max(0, input$cost_point))
  })
  
  # ---- Boxplot render ----
  output$revenue_boxplot <- renderPlot({
    library(ggplot2)
    library(scales)
    library(ggtext)
    
    revenue <- sim_draws()
    rev_est <- revenue_estimate_freq()
    
    # 5th–95th percentile limits
    y_limits <- quantile(revenue, c(0.05, 0.95), na.rm = TRUE)
    
    ggplot(data.frame(revenue = revenue), aes(x = "", y = revenue)) +
      geom_boxplot(
        aes(fill = "Estimated variation in annual revenue (5th–95th percentile)"),
        width = 0.5, outlier.shape = NA
      ) +
      coord_cartesian(ylim = y_limits) +
      labs(
        title = "Projected Annual Revenue of a State MDMA Monopoly",
        x = NULL, y = "Revenue"
      ) +
      scale_y_continuous(labels = label_number(prefix = "€", big.mark = ",")) +
      geom_segment(
        data = data.frame(y = rev_est),
        aes(x = 0.75, xend = 1.25, y = rev_est, yend = rev_est,
            color = "Estimated long-term annual revenue"),
        linewidth = 1
      ) +
      scale_fill_manual(
        values = c("Estimated variation in annual revenue (5th–95th percentile)" = "grey90"),
        labels = c(
          "Estimated variation in annual revenue (5th–95th percentile)" =
            "Estimated variation in annual revenue <br><span style='color:grey50'>(5th–95th percentile)</span>"
        ),
        name = NULL
      ) +
      scale_color_manual(values = c("Estimated long-term annual revenue" = "blue"), name = NULL) +
      guides(
        color = guide_legend(order = 1, override.aes = list(linetype = "solid", linewidth = 1)),
        fill  = guide_legend(order = 2)
      ) +
      theme_minimal(base_size = 13) +
      theme(
        plot.background    = element_rect(fill = "white", color = NA),
        panel.grid.major.x = element_blank(),
        axis.text.x        = element_blank(),
        axis.ticks.x       = element_blank(),
        legend.position    = "bottom",
        legend.text        = element_markdown()
      )
  })
  
  
}

# Run the application 
shinyApp(ui = ui, server = server)
