
library(shiny)

# Define UI for application that draws a histogram
ui <- fluidPage(
  titlePanel("MDMA Monopoly — Revenue Sandbox"),
  tags$p(
    tags$strong("This shiny app compliments the report: Counting the Returns MDMA quickscan, by the municipality of Amsterdam"),
    "The quickscan provides an estimate of the potential revenue that could be generated by a state-run MDMA monopoly in the Netherlands. As there is no precedent for a regulated MDMA market, our analysis is partly based on educated guesses. For instance, we have made assumptions regarding the production costs of MDMA and the proportion of consumers who would switch to a regulated market. This app enables you to easily calculate your own revenue estimates for a state-run MDMA monopoly, based on various assumptions.",
    tags$br(),
    tags$p(
      style = "margin-top: 1rem;",
      "Revenue is calculated using the following formula: ",
      tags$span(
        style = "white-space: nowrap;",
        tags$em("Number of consumers"), " × ",
        tags$em("Intensity"), " × ",
        tags$em("Market capture"), " × (",
        tags$em("Price"), " − ", tags$em("Cost"), ")."
      )
    )
  ),
  hr(),
  
  fluidRow(
    column(
      width = 4,
      h4("Intensity (Normal)"),
      numericInput("intensity_mean", "Mean pills per session (μ)", value = 2, min = 0, step = 0.1),
      numericInput("intensity_sd", "Spread (sd)", value = 0.5, min = 0, step = 0.1)
    ),
    column(
      width = 4,
      h4("Market capture"),
      numericInput("mkr_point", "Point estimate", value = 0.8, min = 0, max = 1, step = 0.01),
      sliderInput("mkr_range", "Range", min = 0, max = 1, value = c(0.4, 0.9), step = 0.01)
    ),
    column(
      width = 4,
      h4("Price & Cost (€/pill)"),
      numericInput("price_point", "Price point estimate", value = 5, min = 0, step = 0.1),
      sliderInput("price_range", "Price range", min = 0, max = 20, value = c(3, 8), step = 0.1),
      numericInput("cost_point", "Cost point estimate", value = 2, min = 0, step = 0.1),
      sliderInput("cost_range", "Cost range", min = 0, max = 20, value = c(1, 8), step = 0.1)
    )
  ),
  hr(),
  fluidRow(
    column(
      width = 12,
      h4("Point estimate (using point inputs)"),
      # Large bold number like a title:
      textOutput("point_estimate", container = h2)
      # If you want it even larger, use container = h1
      # textOutput("point_estimate", container = h1)
    )
  )
)


server <- function(input, output, session) {
  # # Simple validation: clamp capture to [0,1] and avoid negative (already enforced by min/max)
  # observe({
  #   if (input$mkr_point < 0) updateNumericInput(session, "mkr_point", value = 0)
  #   if (input$mkr_point > 1) updateNumericInput(session, "mkr_point", value = 1)
  # })
  
  # Point estimate uses point inputs only (no frequency in this minimal step)
  revenue_point <- reactive({
    mkr  <- input$mkr_point
    p    <- input$price_point
    cst  <- input$cost_point
    inten <- input$intensity_mean
    
    # Ensure non-negative and handle price < cost gracefully (can produce negative revenue)
    mkr <- max(0, min(1, mkr))
    p   <- max(0, p)
    cst <- max(0, cst)
    inten <- max(0, inten)
    
    number_consumers * inten * mkr * (p - cst)
  })
  
  output$point_estimate <- renderPrint({
    # formatted output
    val <- revenue_point()
    paste0("€ ", format(round(val, 0), big.mark = ","))
  })
}

# Run the application 
shinyApp(ui = ui, server = server)
